#cloud-config

users:
  - name: zach
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCudWw3jiJI90peXnoxQV3IDdmXpHdxNVUb6R1bUK42G3sXs89hAv7h3v6cH0GSgFLqRflqwvqiFgXk0nGKAVAxE+zKS06kLgx0/Lidcf7VmQxXrJhEO5X5cLMyvUey7AuvBtSRgJrJy6BMJ8vp5oCctlme3tjxwK80SQ+5ZBJbG0v8eB6E3szsu6rVNGsIcOxUKLAU/HryZbZRMeT8us71xeccmecMEpnM93rS9bv4muf70uuhl2cxs3LllOIx9l1bpRp29NPilACenlKFpFiAvSs8vyJLbmm+uT8bLE93YPLh+iQPXgrSSOiMcdZ421mw5yrpoj0hPGGMUKFw5JXg5G5XzhpS2NcncGd8Zxknw+BNYb/KulWaItnPYG/bBmru8He8jCo8sxaYSrXCrOPLqVOFBwyp5Tl4qcqliAuXulcyDXH2NhLCNnLYlH0IQvxoOzJZZVDO8gawLXoE0I+OfAY5ZFdR4flbVmhTEQ5BJHdvYILxXlz/lbQ5c3697Ik=
    groups: ['sudo']
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
  - name: ansible
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDN9ge5JLcFuX062u6codiozD0LG089HEA858m3qcKVVHjK/vTLk//Ds4AMJLH2o3tCTzgZSXKiAtFHXHg95GYmx8rnC/jO0We3+ATBJYtBKnPnULHaElKiUPFDF28DI2gl6NCQOZwGA2Uab5Cd1fDT8mkcc8uZze7ojTc58xudizzTLXK/b9PMHrTrUax2qk2PcrfjL8JIyNM0mdWroyXuZ+AFKoyg4+7y6uVciTb8tNwLD74Q5+5v9K/OiCwqzzWlx1esM4aobU1DWEqyCDRCujJtDqODtxsuvG+SYmavyKjgtVuIqyaCVSuQQPz+g0vuTsbXDWeWhIOFpSexsKbR0L212uVTcSk2OrQXpssJnEXmQznCkoB16e2DY+uMIYfjqVHXX0t5Ai8v+VLdpDaIUY/ZQUeExv5GEL27fhsUoj69wgIi2n25jmk6WPRnbVcTACqDyJWQsb/fAtNUNNU2kN7V/an+D660I6CsjE69bVtmxhRzf02wRA0G1ycZMq0=
    groups: ['sudo']
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
locale: en_US.UTF-8
timezone: US/East
package_update: true
package_upgrade: true
packages:
  - qemu-guest-agent