---
- hosts: proxmox
  roles:
    - role: bootstrap-proxmox
    - role: iommu-proxmox
    - role: ironicbadger.proxmox_nag_removal
- hosts: container_host
  roles:
    - role: hostname
    - role: container-host
    - role: deb-updates
    - role: second-disk