- name: Install packages
  ansible.builtin.apt:
    pkg:
      - git
      - curl
      - docker.io
      - docker-compose
    state: latest
    update_cache: yes
  become: true
- name: Add user to Docker Users
  user:
    name: "{{ docker_user }}"
    state: present
    shell: /bin/bash
    groups: sudo,docker
    append: yes
  become: true